services:
  db:
    image: mysql:8.0
    container_name: forum-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: forumuser
      MYSQL_PASSWORD: forumpassword
      MYSQL_DATABASE: forumdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/forumdb.sql:/docker-entrypoint-initdb.d/forumdb.sql 

volumes:
  mysql_data: