version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: forum-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forumdb
      MYSQL_USER: forumuser
      MYSQL_PASSWORD: forumpassword
    ports:
      - "3306:3306"
    volumes:
      - ./internal/database/dump.sql:/docker-entrypoint-initdb.d/init.sql
